<?php

namespace Database\Seeders;

use App\Models\Party;
use Illuminate\Database\Seeder;

class PartySeeder extends Seeder
{
    /**
     * ข้อมูลพรรคการเมืองหลัก อ้างอิงจาก กกต. (สำนักงานคณะกรรมการการเลือกตั้ง)
     * https://www.ect.go.th/
     * https://party.ect.go.th/party-info
     *
     * อัปเดตล่าสุด: เลือกตั้ง 8 กุมภาพันธ์ 2569 (2026)
     * ข้อมูลจากการจับสลากเลขที่พรรค วันที่ 28 ธันวาคม 2568
     *
     * หมายเหตุ: พรรคก้าวไกลถูกยุบ 7 สิงหาคม 2567 -> แทนที่ด้วยพรรคประชาชน
     */
    public function run(): void
    {
        $parties = [
            // พรรคหลัก (Top 10 Major Parties by popularity/seats)
            [
                'name_th' => 'พรรคประชาชน',
                'name_en' => "People's Party",
                'abbreviation' => 'ปชช.',
                'color' => '#FF6B00',
                'secondary_color' => '#FF8C33',
                'leader_name' => 'นทีธร บุญประคม',
                'founded_year' => 2024,
                'logo' => null,
                'website' => 'https://peoplesparty.or.th',
                'party_number' => 46,
                'is_active' => true,
                'description' => 'พรรคประชาชนเป็นพรรคการเมืองก้าวหน้าที่สืบทอดอุดมการณ์จากพรรคก้าวไกล (ถูกยุบ 7 สิงหาคม 2567) ใช้สีส้มเป็นสัญลักษณ์',
            ],
            [
                'name_th' => 'พรรคเพื่อไทย',
                'name_en' => 'Pheu Thai Party',
                'abbreviation' => 'พท.',
                'color' => '#E31E25',
                'secondary_color' => '#FF4D52',
                'leader_name' => 'แพทองธาร ชินวัตร',
                'founded_year' => 2008,
                'logo' => null,
                'website' => 'https://ptp.or.th',
                'party_number' => 9,
                'is_active' => true,
                'description' => 'พรรคการเมืองรัฐบาลปัจจุบัน นำโดยนางสาวแพทองธาร ชินวัตร',
            ],
            [
                'name_th' => 'พรรคภูมิใจไทย',
                'name_en' => 'Bhumjaithai Party',
                'abbreviation' => 'ภท.',
                'color' => '#0066B3',
                'secondary_color' => '#3399CC',
                'leader_name' => 'อนุทิน ชาญวีรกูล',
                'founded_year' => 2008,
                'logo' => null,
                'website' => 'https://www.bhumjaithai.com',
                'party_number' => 37,
                'is_active' => true,
                'description' => 'พรรคร่วมรัฐบาล นำโดยนายอนุทิน ชาญวีรกูล',
            ],
            [
                'name_th' => 'พรรคประชาธิปัตย์',
                'name_en' => 'Democrat Party',
                'abbreviation' => 'ปชป.',
                'color' => '#00AEEF',
                'secondary_color' => '#66D3FF',
                'leader_name' => 'จุรินทร์ ลักษณวิศิษฏ์',
                'founded_year' => 1946,
                'logo' => null,
                'website' => 'https://www.democrat.or.th',
                'party_number' => 27,
                'is_active' => true,
                'description' => 'พรรคการเมืองเก่าแก่ที่สุดในประเทศไทย ก่อตั้งปี พ.ศ. 2489',
            ],
            [
                'name_th' => 'พรรคพลังประชารัฐ',
                'name_en' => 'Palang Pracharath Party',
                'abbreviation' => 'พปชร.',
                'color' => '#1E3A8A',
                'secondary_color' => '#3B5998',
                'leader_name' => 'ประวิตร วงษ์สุวรรณ',
                'founded_year' => 2018,
                'logo' => null,
                'website' => 'https://www.pprp.or.th',
                'party_number' => 43,
                'is_active' => true,
                'description' => 'พรรคการเมืองที่สนับสนุนรัฐบาล คสช. ในอดีต',
            ],
            [
                'name_th' => 'พรรคไทยสร้างไทย',
                'name_en' => 'Thai Sang Thai Party',
                'abbreviation' => 'ทสท.',
                'color' => '#FFC107',
                'secondary_color' => '#FFD54F',
                'leader_name' => 'คุณหญิงสุดารัตน์ เกยุราพันธุ์',
                'founded_year' => 2021,
                'logo' => null,
                'website' => 'https://thaisangthai.org',
                'party_number' => 48,
                'is_active' => true,
                'description' => 'พรรคการเมืองนำโดยคุณหญิงสุดารัตน์ เกยุราพันธุ์',
            ],
            [
                'name_th' => 'พรรคประชาธิปไตยใหม่',
                'name_en' => 'New Democracy Party',
                'abbreviation' => 'ปชธ.',
                'color' => '#2E8B57',
                'secondary_color' => '#3CB371',
                'leader_name' => 'สุรทิน พิจารณ์',
                'founded_year' => 2022,
                'logo' => null,
                'website' => null,
                'party_number' => 8,
                'is_active' => true,
                'description' => 'พรรคการเมืองใหม่ เน้นนโยบายประชาธิปไตย',
            ],
            [
                'name_th' => 'พรรคเสรีรวมไทย',
                'name_en' => 'Seri Ruam Thai Party',
                'abbreviation' => 'สรท.',
                'color' => '#FF69B4',
                'secondary_color' => '#FF1493',
                'leader_name' => 'พลตำรวจเอก เสรีพิศุทธ์ เตมียเวส',
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => 12,
                'is_active' => true,
                'description' => 'พรรคเสรีรวมไทย เน้นเสรีภาพและประชาธิปไตย',
            ],
            [
                'name_th' => 'พรรคกล้าธรรม',
                'name_en' => 'Kla Dharma Party',
                'abbreviation' => 'กธ.',
                'color' => '#4B0082',
                'secondary_color' => '#8B008B',
                'leader_name' => 'กัปตัน ธรรมนัส พรหมเผ่า',
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 42,
                'is_active' => true,
                'description' => 'พรรคการเมืองนำโดยกัปตัน ธรรมนัส พรหมเผ่า อดีต รมว.เกษตรและสหกรณ์',
            ],
            [
                'name_th' => 'พรรครวมจิตไทย',
                'name_en' => 'Ruam Jai Thai Party',
                'abbreviation' => 'รจท.',
                'color' => '#006400',
                'secondary_color' => '#228B22',
                'leader_name' => null,
                'founded_year' => 2021,
                'logo' => null,
                'website' => null,
                'party_number' => 5,
                'is_active' => true,
                'description' => 'พรรครวมจิตไทย',
            ],
            [
                'name_th' => 'พรรคทางเลือกใหม่',
                'name_en' => 'New Alternative Party',
                'abbreviation' => 'ทลม.',
                'color' => '#800080',
                'secondary_color' => '#9370DB',
                'leader_name' => null,
                'founded_year' => 2022,
                'logo' => null,
                'website' => null,
                'party_number' => 10,
                'is_active' => true,
                'description' => 'พรรคทางเลือกใหม่',
            ],
            [
                'name_th' => 'พรรครวมพลังประชาชน',
                'name_en' => 'Ruam Palang Prachachon Party',
                'abbreviation' => 'รพช.',
                'color' => '#8B0000',
                'secondary_color' => '#DC143C',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 13,
                'is_active' => true,
                'description' => 'พรรครวมพลังประชาชน',
            ],

            // พรรคอื่นๆ ที่จับสลากเลขที่พรรค 2026 (52 พรรค)
            [
                'name_th' => 'พรรคไทยสัพท์ทวี',
                'name_en' => 'Thai Sap Thawi Party',
                'abbreviation' => 'ทสว.',
                'color' => '#B8860B',
                'secondary_color' => '#DAA520',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 1,
                'is_active' => true,
                'description' => 'พรรคไทยสัพท์ทวี',
            ],
            [
                'name_th' => 'พรรคเพื่อชาติไทย',
                'name_en' => 'Pheu Chart Thai Party',
                'abbreviation' => 'พชท.',
                'color' => '#CD5C5C',
                'secondary_color' => '#F08080',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => 2,
                'is_active' => true,
                'description' => 'พรรคเพื่อชาติไทย',
            ],
            [
                'name_th' => 'พรรคใหม่',
                'name_en' => 'New Party',
                'abbreviation' => 'ใหม่',
                'color' => '#20B2AA',
                'secondary_color' => '#48D1CC',
                'leader_name' => null,
                'founded_year' => 2021,
                'logo' => null,
                'website' => null,
                'party_number' => 3,
                'is_active' => true,
                'description' => 'พรรคใหม่',
            ],
            [
                'name_th' => 'พรรคมิติใหม่',
                'name_en' => 'New Dimension Party',
                'abbreviation' => 'มม.',
                'color' => '#4682B4',
                'secondary_color' => '#5F9EA0',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 4,
                'is_active' => true,
                'description' => 'พรรคมิติใหม่',
            ],
            [
                'name_th' => 'พรรครวมไทยสร้างชาติ',
                'name_en' => 'Ruam Thai Sang Chart Party',
                'abbreviation' => 'รทสช.',
                'color' => '#9370DB',
                'secondary_color' => '#BA55D3',
                'leader_name' => null,
                'founded_year' => 2021,
                'logo' => null,
                'website' => null,
                'party_number' => 6,
                'is_active' => true,
                'description' => 'พรรครวมไทยสร้างชาติ',
            ],
            [
                'name_th' => 'พรรคพลวัต',
                'name_en' => 'Phonlawat Party',
                'abbreviation' => 'พลวัต',
                'color' => '#FF4500',
                'secondary_color' => '#FF6347',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 7,
                'is_active' => true,
                'description' => 'พรรคพลวัต',
            ],
            [
                'name_th' => 'พรรคเศรษฐกิจ',
                'name_en' => 'Economic Party',
                'abbreviation' => 'ศก.',
                'color' => '#228B22',
                'secondary_color' => '#32CD32',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => 11,
                'is_active' => true,
                'description' => 'พรรคเศรษฐกิจ',
            ],
            [
                'name_th' => 'พรรคท้องถิ่นไทย',
                'name_en' => 'Thongthi Thai Party',
                'abbreviation' => 'ทถท.',
                'color' => '#D2691E',
                'secondary_color' => '#CD853F',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 14,
                'is_active' => true,
                'description' => 'พรรคท้องถิ่นไทย',
            ],
            [
                'name_th' => 'พรรคอนาคตไทย',
                'name_en' => 'Thai Future Party',
                'abbreviation' => 'อท.',
                'color' => '#1E90FF',
                'secondary_color' => '#00BFFF',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 15,
                'is_active' => true,
                'description' => 'พรรคอนาคตไทย',
            ],
            [
                'name_th' => 'พรรคพลังเพื่อไทย',
                'name_en' => 'Power for Thai Party',
                'abbreviation' => 'พพท.',
                'color' => '#DC143C',
                'secondary_color' => '#FF1493',
                'leader_name' => null,
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => 16,
                'is_active' => true,
                'description' => 'พรรคพลังเพื่อไทย',
            ],
            [
                'name_th' => 'พรรคไทยชนะ',
                'name_en' => 'Thai Chana Party',
                'abbreviation' => 'ทชน.',
                'color' => '#FF8C00',
                'secondary_color' => '#FFA500',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => 17,
                'is_active' => true,
                'description' => 'พรรคไทยชนะ',
            ],
            [
                'name_th' => 'พรรคพลังสังคมใหม่',
                'name_en' => 'New Social Power Party',
                'abbreviation' => 'พสม.',
                'color' => '#9932CC',
                'secondary_color' => '#BA55D3',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 18,
                'is_active' => true,
                'description' => 'พรรคพลังสังคมใหม่',
            ],
            [
                'name_th' => 'พรรคสังคมประชาธิปไตยไทย',
                'name_en' => 'Social Democracy Party',
                'abbreviation' => 'สปท.',
                'color' => '#8B4513',
                'secondary_color' => '#A0522D',
                'leader_name' => null,
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => 19,
                'is_active' => true,
                'description' => 'พรรคสังคมประชาธิปไตยไทย',
            ],
            [
                'name_th' => 'พรรคฟิวชั่น',
                'name_en' => 'Fusion Party',
                'abbreviation' => 'ฟช.',
                'color' => '#FF1493',
                'secondary_color' => '#FF69B4',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 20,
                'is_active' => true,
                'description' => 'พรรคฟิวชั่น',
            ],
            [
                'name_th' => 'พรรคใสรวมพลัง',
                'name_en' => 'Sai Ruam Palang Party',
                'abbreviation' => 'สรพ.',
                'color' => '#87CEEB',
                'secondary_color' => '#87CEFA',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => 21,
                'is_active' => true,
                'description' => 'พรรคใสรวมพลัง',
            ],
            [
                'name_th' => 'พรรคเก่าอิสระ',
                'name_en' => 'Kao Issara Party',
                'abbreviation' => 'กอ.',
                'color' => '#6B8E23',
                'secondary_color' => '#808000',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 22,
                'is_active' => true,
                'description' => 'พรรคเก่าอิสระ',
            ],
            [
                'name_th' => 'พรรคปวงชนไทย',
                'name_en' => 'Puangchon Thai Party',
                'abbreviation' => 'ปท.',
                'color' => '#B22222',
                'secondary_color' => '#DC143C',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => 23,
                'is_active' => true,
                'description' => 'พรรคปวงชนไทย',
            ],
            [
                'name_th' => 'พรรควิสัยทัศน์ใหม่',
                'name_en' => 'New Vision Party',
                'abbreviation' => 'วม.',
                'color' => '#4169E1',
                'secondary_color' => '#6495ED',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 24,
                'is_active' => true,
                'description' => 'พรรควิสัยทัศน์ใหม่',
            ],
            [
                'name_th' => 'พรรคเพื่อชีวิตใหม่',
                'name_en' => 'Pheu Cheewit Mai Party',
                'abbreviation' => 'พชม.',
                'color' => '#00CED1',
                'secondary_color' => '#40E0D0',
                'leader_name' => null,
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => 25,
                'is_active' => true,
                'description' => 'พรรคเพื่อชีวิตใหม่',
            ],
            [
                'name_th' => 'พรรคคลองไทย',
                'name_en' => 'Khlong Thai Party',
                'abbreviation' => 'คท.',
                'color' => '#2F4F4F',
                'secondary_color' => '#708090',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => 26,
                'is_active' => true,
                'description' => 'พรรคคลองไทย',
            ],
            [
                'name_th' => 'พรรคไทยก้าวหน้า',
                'name_en' => 'Thai Progressive Party',
                'abbreviation' => 'ทกห.',
                'color' => '#FF00FF',
                'secondary_color' => '#FF00FF',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 28,
                'is_active' => true,
                'description' => 'พรรคไทยก้าวหน้า',
            ],
            [
                'name_th' => 'พรรคไทยภักดี',
                'name_en' => 'Thai Phakdee Party',
                'abbreviation' => 'ทภ.',
                'color' => '#FFD700',
                'secondary_color' => '#F0E68C',
                'leader_name' => null,
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => 29,
                'is_active' => true,
                'description' => 'พรรคไทยภักดี',
            ],
            [
                'name_th' => 'พรรคแรงงานสร้างชาติ',
                'name_en' => 'Labor to Build the Nation Party',
                'abbreviation' => 'รสช.',
                'color' => '#FF4500',
                'secondary_color' => '#FF6347',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => 30,
                'is_active' => true,
                'description' => 'พรรคแรงงานสร้างชาติ',
            ],
            [
                'name_th' => 'พรรคประชารัฐไทย',
                'name_en' => 'Pracharat Thai Party',
                'abbreviation' => 'ปรท.',
                'color' => '#4B0082',
                'secondary_color' => '#8B008B',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 31,
                'is_active' => true,
                'description' => 'พรรคประชารัฐไทย',
            ],
            [
                'name_th' => 'พรรคครูไทยเพื่อประชาชน',
                'name_en' => 'Teachers for the People Party',
                'abbreviation' => 'ครูท.',
                'color' => '#008B8B',
                'secondary_color' => '#20B2AA',
                'leader_name' => null,
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => 32,
                'is_active' => true,
                'description' => 'พรรคครูไทยเพื่อประชาชน',
            ],
            [
                'name_th' => 'พรรคประชาชาติ',
                'name_en' => 'Pracha Chat Party',
                'abbreviation' => 'ปชช.',
                'color' => '#2E8B57',
                'secondary_color' => '#3CB371',
                'leader_name' => null,
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => 33,
                'is_active' => true,
                'description' => 'พรรคประชาชาติ',
            ],
            [
                'name_th' => 'พรรคสร้างอนาคตไทย',
                'name_en' => 'Build the Future Thai Party',
                'abbreviation' => 'สอท.',
                'color' => '#8B4513',
                'secondary_color' => '#A0522D',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 34,
                'is_active' => true,
                'description' => 'พรรคสร้างอนาคตไทย',
            ],
            [
                'name_th' => 'พรรครักชาติ',
                'name_en' => 'Rak Chat Party',
                'abbreviation' => 'รช.',
                'color' => '#FF6347',
                'secondary_color' => '#FF7F50',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => 35,
                'is_active' => true,
                'description' => 'พรรครักชาติ',
            ],
            [
                'name_th' => 'พรรคไทยพร้อม',
                'name_en' => 'Thai Prom Party',
                'abbreviation' => 'ทพร.',
                'color' => '#4169E1',
                'secondary_color' => '#6495ED',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 36,
                'is_active' => true,
                'description' => 'พรรคไทยพร้อม',
            ],
            [
                'name_th' => 'พรรคพลังธรรมใหม่',
                'name_en' => 'New Dharma Power Party',
                'abbreviation' => 'พธม.',
                'color' => '#8A2BE2',
                'secondary_color' => '#9370DB',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => 38,
                'is_active' => true,
                'description' => 'พรรคพลังธรรมใหม่',
            ],
            [
                'name_th' => 'พรรคกรีน',
                'name_en' => 'Green Party',
                'abbreviation' => 'กรีน',
                'color' => '#228B22',
                'secondary_color' => '#32CD32',
                'leader_name' => null,
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => 39,
                'is_active' => true,
                'description' => 'พรรคกรีน เน้นนโยบายสิ่งแวดล้อมและความยั่งยืน',
            ],
            [
                'name_th' => 'พรรคไทยธรรม',
                'name_en' => 'Thai Dharma Party',
                'abbreviation' => 'ทธ.',
                'color' => '#DAA520',
                'secondary_color' => '#FFD700',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => 40,
                'is_active' => true,
                'description' => 'พรรคไทยธรรม',
            ],
            [
                'name_th' => 'พรรคแผ่นดินธรรม',
                'name_en' => 'Phandin Dharma Party',
                'abbreviation' => 'พธ.',
                'color' => '#CD853F',
                'secondary_color' => '#D2691E',
                'leader_name' => null,
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => 41,
                'is_active' => true,
                'description' => 'พรรคแผ่นดินธรรม',
            ],
            [
                'name_th' => 'พรรคโอกาสใหม่',
                'name_en' => 'New Opportunity Party',
                'abbreviation' => 'อม.',
                'color' => '#FF8C00',
                'secondary_color' => '#FFA500',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 44,
                'is_active' => true,
                'description' => 'พรรคโอกาสใหม่',
            ],
            [
                'name_th' => 'พรรคเป็นธรรม',
                'name_en' => 'Pen Tham Party',
                'abbreviation' => 'ปธ.',
                'color' => '#008B8B',
                'secondary_color' => '#20B2AA',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => 45,
                'is_active' => true,
                'description' => 'พรรคเป็นธรรม',
            ],
            [
                'name_th' => 'พรรคประชาไทย',
                'name_en' => 'Pracha Thai Party',
                'abbreviation' => 'ปท.',
                'color' => '#DC143C',
                'secondary_color' => '#FF1493',
                'leader_name' => null,
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => 47,
                'is_active' => true,
                'description' => 'พรรคประชาไทย',
            ],
            [
                'name_th' => 'พรรคไทยเก่าใหม่',
                'name_en' => 'Thai Kao Mai Party',
                'abbreviation' => 'ทกม.',
                'color' => '#8B4513',
                'secondary_color' => '#A0522D',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 49,
                'is_active' => true,
                'description' => 'พรรคไทยเก่าใหม่',
            ],
            [
                'name_th' => 'พรรคประชาอาษาชาติ',
                'name_en' => 'Pracha Asa Chat Party',
                'abbreviation' => 'ปอช.',
                'color' => '#4682B4',
                'secondary_color' => '#5F9EA0',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => 50,
                'is_active' => true,
                'description' => 'พรรคประชาอาษาชาติ',
            ],
            [
                'name_th' => 'พรรคพร้อม',
                'name_en' => 'Prom Party',
                'abbreviation' => 'พร.',
                'color' => '#9370DB',
                'secondary_color' => '#BA55D3',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 51,
                'is_active' => true,
                'description' => 'พรรคพร้อม',
            ],
            [
                'name_th' => 'พรรคเครือข่ายชาวนาแห่งประเทศไทย',
                'name_en' => 'Network of Farmers of Thailand Party',
                'abbreviation' => 'ครท.',
                'color' => '#228B22',
                'secondary_color' => '#32CD32',
                'leader_name' => null,
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => 52,
                'is_active' => true,
                'description' => 'พรรคเครือข่ายชาวนาแห่งประเทศไทย',
            ],

            // พรรคเพิ่มเติม (ที่ไม่ได้จับสลากแต่ยังดำเนินการอยู่)
            [
                'name_th' => 'พรรคไทยรวมไทย',
                'name_en' => 'Thai Rukam Thai Party',
                'abbreviation' => 'ทรท.',
                'color' => '#B8860B',
                'secondary_color' => '#DAA520',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 55,
                'is_active' => true,
                'description' => 'พรรคไทยรวมไทย ลงทะเบียนวันสุดท้าย 31 ธันวาคม 2568',
            ],
            [
                'name_th' => 'พรรคเพื่อบ้านเมือง',
                'name_en' => 'Phuea Ban Muang Party',
                'abbreviation' => 'พบม.',
                'color' => '#4169E1',
                'secondary_color' => '#6495ED',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 56,
                'is_active' => true,
                'description' => 'พรรคเพื่อบ้านเมือง ลงทะเบียนวันสุดท้าย 31 ธันวาคม 2568',
            ],
            [
                'name_th' => 'พรรคพลังไทยรักชาติ',
                'name_en' => 'Palang Thai Rak Chat Party',
                'abbreviation' => 'พทรช.',
                'color' => '#DC143C',
                'secondary_color' => '#FF1493',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => 57,
                'is_active' => true,
                'description' => 'พรรคพลังไทยรักชาติ ลงทะเบียนวันสุดท้าย 31 ธันวาคม 2568',
            ],
            [
                'name_th' => 'พรรคชาติไทยพัฒนา',
                'name_en' => 'Chart Thai Pattana Party',
                'abbreviation' => 'ชทพ.',
                'color' => '#FF8C00',
                'secondary_color' => '#FFA500',
                'leader_name' => 'วราวุธ ศิลปอาชา',
                'founded_year' => 2008,
                'logo' => null,
                'website' => null,
                'party_number' => null,
                'is_active' => true,
                'description' => 'พรรคชาติไทยพัฒนา พรรคการเมืองที่มีประวัติยาวนาน',
            ],
            [
                'name_th' => 'พรรคความหวังใหม่',
                'name_en' => 'New Hope Party',
                'abbreviation' => 'คหม.',
                'color' => '#20B2AA',
                'secondary_color' => '#48D1CC',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => null,
                'is_active' => true,
                'description' => 'พรรคความหวังใหม่',
            ],
            [
                'name_th' => 'พรรคเพื่อชาติ',
                'name_en' => 'For Nation Party',
                'abbreviation' => 'พช.',
                'color' => '#CD5C5C',
                'secondary_color' => '#F08080',
                'leader_name' => null,
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => null,
                'is_active' => true,
                'description' => 'พรรคเพื่อชาติ',
            ],
            [
                'name_th' => 'พรรคประชากรไทย',
                'name_en' => 'Thai Population Party',
                'abbreviation' => 'ปท.',
                'color' => '#4682B4',
                'secondary_color' => '#5F9EA0',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => null,
                'is_active' => true,
                'description' => 'พรรคประชากรไทย',
            ],
            [
                'name_th' => 'พรรครักษ์ธรรม',
                'name_en' => 'Dharma Protection Party',
                'abbreviation' => 'รธ.',
                'color' => '#DAA520',
                'secondary_color' => '#FFD700',
                'leader_name' => null,
                'founded_year' => 2019,
                'logo' => null,
                'website' => null,
                'party_number' => null,
                'is_active' => true,
                'description' => 'พรรครักษ์ธรรม',
            ],
            [
                'name_th' => 'พรรคพลังประชาธิปไตย',
                'name_en' => 'Democratic Power Party',
                'abbreviation' => 'พปธ.',
                'color' => '#1E90FF',
                'secondary_color' => '#00BFFF',
                'leader_name' => null,
                'founded_year' => 2018,
                'logo' => null,
                'website' => null,
                'party_number' => null,
                'is_active' => true,
                'description' => 'พรรคพลังประชาธิปไตย',
            ],
            [
                'name_th' => 'พรรคไทยศรีวิไลย์',
                'name_en' => 'Thai Sri Wilaiyh Party',
                'abbreviation' => 'ทศว.',
                'color' => '#9370DB',
                'secondary_color' => '#BA55D3',
                'leader_name' => null,
                'founded_year' => 2020,
                'logo' => null,
                'website' => null,
                'party_number' => null,
                'is_active' => true,
                'description' => 'พรรคไทยศรีวิไลย์',
            ],
        ];

        $created = 0;
        $updated = 0;

        foreach ($parties as $partyData) {
            $party = Party::where('name_th', $partyData['name_th'])->first();

            if ($party) {
                // Update existing party if data changed
                $party->update($partyData);
                $updated++;
            } else {
                // Create new party
                Party::create($partyData);
                $created++;
            }
        }

        $this->command->info("Parties: {$created} created, {$updated} updated.");
    }
}
